### ISSUE TITLE
Создать логику добавления экскурсии

### ISSUE THREAD

**Issue by Gyxer513** [LiteraExcurs/backend#1]
Необходимо создать CRUD логику активности в backend.

Логика должна содержать:

- Добавление новой активности

- Обновление активности

- Удаление активности

**Comment by Gyxer513** [comment]
Дополнительно в этой задаче нужно настроить подключение к базе

**Comment by anastasia-bazaeva** [comment]
@Gyxer513 Привет! Как и обещала, подумала над предложениями по структуре данных. Ниже схемка в пдф, она вполне подлежит дискуссии. 


[Модели данных (1).pdf](https://github.com/LiteraExcurs/backend/files/12916426/1.pdf)

**Comment by Gyxer513** [comment]
@anastasia-bazaeva Привет! Спасибо! Взял в работу, только PG не умеет хранить массивы, создавать на каждую экскурсию по дополнительной таблице не выход. Пока пропущу все столбцы с массивами.

**Comment by anastasia-bazaeva** [comment]
Там одно только поле с массивом из предложенных - для доступных дней недели. Просто не хотелось бы делать отдельную сущность для дней недели. Поставила там массив на всякий случай, т.к. PG умеет хранить JSON в виде строки, в котором уже можно будет как раз и массив хранить. Ну либо сделать 7 полей на каждый день недели и хранить булево значение, которое покажет, в какие дни может быть доступно событие.
